import { readFile, rename, writeFile } from 'node:fs/promises'
import {
  CATEGORY_TITLES,
  MARKER_END,
  MARKER_START,
  MemoryCategory,
  SyncFailure,
  err,
  ok,
  type Result,
} from './core.ts'
import type { MemoryEntry } from './memory.ts'
import { isAnchoredToProject } from './vocabulary.ts'

const MAX_BULLETS_PER_ENTRY = 6
const MAX_BULLET_LENGTH = 280
const MAX_ENTRIES_PER_CATEGORY = 4
const BULLET_PATTERN = /^\s*[-*]\s+(.*)$/

export type BlockMetadata = {
  readonly project: string
  readonly windowDays: number
  readonly generatedAt: string
}

export type BulletFilters = {
  readonly vocabulary: ReadonlySet<string>
  readonly deniedTerms: ReadonlyArray<string>
}

const mentionsDeniedTerm = (bullet: string, deniedTerms: ReadonlyArray<string>): boolean => {
  const lowered = bullet.toLowerCase()
  return deniedTerms.some((term) => {
    const trimmed = term.trim().toLowerCase()
    return trimmed.length > 0 && lowered.includes(trimmed)
  })
}

const stripMarkdownEmphasis = (line: string): string => line.replace(/\*\*/g, '').trim()

const extractBullets = (text: string, filters: BulletFilters): ReadonlyArray<string> => {
  const bullets: string[] = []

  for (const line of text.split(/\r?\n/)) {
    const match = BULLET_PATTERN.exec(line)
    if (!match) continue

    const content = stripMarkdownEmphasis(match[1] ?? '')
    if (content.length === 0) continue
    if (mentionsDeniedTerm(content, filters.deniedTerms)) continue
    if (!isAnchoredToProject(content, filters.vocabulary)) continue

    bullets.push(content.length > MAX_BULLET_LENGTH ? `${content.slice(0, MAX_BULLET_LENGTH)}…` : content)
    if (bullets.length === MAX_BULLETS_PER_ENTRY) break
  }

  return bullets
}

const renderEntry = (entry: MemoryEntry, filters: BulletFilters): string | null => {
  const bullets = extractBullets(entry.text, filters)
  if (bullets.length === 0) return null

  const day = entry.createdAt.slice(0, 10)
  const lines = [`**${entry.title}** — ${day}`, '', ...bullets.map((bullet) => `- ${bullet}`)]
  return lines.join('\n')
}

export const composeBlock = (
  entries: ReadonlyArray<MemoryEntry>,
  metadata: BlockMetadata,
  filters: BulletFilters,
): string => {
  const sections: string[] = [
    MARKER_START,
    '',
    '## Project memory',
    '',
    `Generated by pieces-to-agents from Pieces Long-Term Memory — project "${metadata.project}", last ${metadata.windowDays} days, on ${metadata.generatedAt}.`,
    '',
  ]

  for (const category of Object.values(MemoryCategory)) {
    const rendered = entries
      .filter((entry) => entry.category === category)
      .slice(0, MAX_ENTRIES_PER_CATEGORY)
      .map((entry) => renderEntry(entry, filters))
      .filter((block): block is string => block !== null)

    if (rendered.length === 0) continue

    sections.push(`### ${CATEGORY_TITLES[category]}`, '', ...rendered.flatMap((block) => [block, '']))
  }

  sections.push(MARKER_END)
  return sections.join('\n')
}

export const spliceManagedBlock = (
  existing: string,
  block: string,
): Result<string, SyncFailure> => {
  const startIndex = existing.indexOf(MARKER_START)
  const endIndex = existing.indexOf(MARKER_END)

  if (startIndex === -1 && endIndex === -1) {
    const separator = existing.trimEnd().length === 0 ? '' : `${existing.trimEnd()}\n\n`
    return ok(`${separator}${block}\n`)
  }

  if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
    return err(SyncFailure.ManagedBlockConflict)
  }

  const before = existing.slice(0, startIndex)
  const after = existing.slice(endIndex + MARKER_END.length)
  return ok(`${before}${block}${after}`)
}

export const readTarget = async (path: string): Promise<Result<string, SyncFailure>> => {
  try {
    return ok(await readFile(path, 'utf8'))
  } catch (caught) {
    if (isMissingFile(caught)) return ok('')
    return err(SyncFailure.ReadFailed)
  }
}

export const writeTarget = async (path: string, content: string): Promise<Result<void, SyncFailure>> => {
  const temporaryPath = `${path}.pieces-tmp`

  try {
    await writeFile(temporaryPath, content, 'utf8')
    await rename(temporaryPath, path)
    return ok(undefined)
  } catch {
    return err(SyncFailure.WriteFailed)
  }
}

const isMissingFile = (caught: unknown): boolean =>
  typeof caught === 'object' &&
  caught !== null &&
  'code' in caught &&
  (caught as { code?: unknown }).code === 'ENOENT'
